sudo: required
language: generic 

services: 
    - docker

before_install:
    - docker build -t ellenlowy/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true ellenlowy/docker-react npm run test
